/**
 * Extension-local re-export of `mergeSnapshot` from core.
 */
export {
  MERGE_SNAPSHOT_SESSION_ID,
  DEFAULT_SNAPSHOT_GROUP_SIZE,
  snapshotVirtualSessionId,
  isMergeSnapshotSessionId,
  filterRealSessionRecords,
  mergeSnapshotPath,
  snapshotManifestPath,
  projectSnapshotsDir,
  snapshotFilePath,
  readMergeSnapshot,
  writeMergeSnapshot,
  deleteMergeSnapshot,
  createEmptySnapshotManifest,
  readSnapshotManifest,
  writeSnapshotManifest,
  readSnapshotById,
  writeSnapshotByPath,
  findLeafNodeForSession,
  findParentNode,
  deleteSnapshotHierarchy,
  buildMergeSnapshotFromVirtualSession,
  buildMergeSnapshotFromOntology,
  snapshotToSessionRecord,
  topRootsFromRecords,
  batchIntroducesNewTopRoots,
  appendReattachSteps,
  type BuildMergeSnapshotMetaExtras,
} from "@agent-mindmap/core";
